version: '3'
services:
  db:
    image: postgis/postgis
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: LeqLgAZ67SQvBEDR
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/consul
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./docker/rails.env
