# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '71451952a81dd37c286c6ea50a683592'
  config.secret_key = '0233df8f6af7f6e8768b2eddaffc5606'
  config.default_from = 'denial.torres@gmail.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
# 
# email = { :from_email   => "denialtorres@gmail.com",
#           :from_name    => "Your name",
#           :subject      => "Hello",
#           :text_part    => "Hi",
#           :recipients   => [{:email => "danielt@cratebind.com"}] }
#
#
#           Mailjet::Send.create(messages: [{
#         'From'=> {
#             'Email'=> 'denial.torres@gmail.com',
#             'Name'=> 'Mailjet Pilot'
#         },
#         'To'=> [
#             {
#                 'Email'=> 'denial.torres@gmail.com',
#                 'Name'=> 'test'
#             }
#         ],
#         'Subject'=> 'Your email flight plan!',
#         'TextPart'=> 'Dear , welcome to Mailjet! May the delivery force be with you!',
#         'HTMLPart'=> '<h3>Dear, welcome to Mailjet!</h3><br />May the delivery force be with you!'
#     }])
