default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'consul' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { '' } %>

development:
  <<: *default
  database: consul_dev

test:
  <<: *default
  database: consul_test

production:
  database: consul_production
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>
  pool: 5
  timeout: 5000
